---
- name: make config directory
  become: yes
  file:
    path: "{{ magicmirror_config_dir }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: copy config file
  template:
    src: config.js.j2
    dest: "{{ magicmirror_config_dir }}/config.js"
  register: config

- name: fetch default modules
  git:
    repo: "{{ magicmirror_repo }}"
    dest: "{{ magicmirror_module_dir }}/MagicMirror"
    version: "{{ magicmirror_default_module_version }}"

- name: copy default modules
  copy:
    src: "{{ magicmirror_module_dir }}/MagicMirror/modules/default"
    dest: "{{ magicmirror_module_dir }}"
    remote_src: yes
  register: default_modules

- name: copy custom modules from Git repo
  git:
    repo: "{{ item.repo }}"
    dest: "{{ magicmirror_module_dir }}/{{ item.name }}"
    version: "{{ item.version }}"
  with_items: "{{ magicmirror_custom_modules }}"
  register: custom_modules

- name: run magicmirror container
  docker_container:
    name: "{{ magicmirror_container_name }}"
    image: "bastilimbach/docker-magicmirror:{{ magicmirror_version }}"
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ magicmirror_config_dir }}:/opt/magic_mirror/config"
      - "{{ magicmirror_module_dir }}:/opt/magic_mirror/modules"
    restart_policy: unless-stopped
    restart: yes
    recreate: yes
  when: config is changed
        or default_modules is changed
        or custom_modules is changed
